/********************************************************************************
** Form generated from reading UI file 'mainwindow.ui'
**
** Created by: Qt User Interface Compiler version 6.5.0
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_MAINWINDOW_H
#define UI_MAINWINDOW_H

#include <QtCore/QVariant>
#include <QtGui/QIcon>
#include <QtWidgets/QApplication>
#include <QtWidgets/QLabel>
#include <QtWidgets/QMainWindow>
#include <QtWidgets/QMenuBar>
#include <QtWidgets/QPushButton>
#include <QtWidgets/QStatusBar>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_MainWindow
{
public:
    QWidget *centralwidget;
    QLabel *label;
    QPushButton *ver_f4;
    QPushButton *pushButton_FabricaMixta;
    QPushButton *pOsf4;
    QLabel *vercolaf4;
    QPushButton *pOsfA;
    QPushButton *pushButton_12;
    QPushButton *colaFA;
    QLabel *label_2;
    QLabel *labelCA;
    QPushButton *vercompfA;
    QPushButton *ColaFB;
    QLabel *labelColaB;
    QLabel *label_4;
    QPushButton *pushButton_9;
    QLabel *vercompf4;
    QPushButton *pushButton_2;
    QPushButton *pushButton_35;
    QLabel *label_15;
    QLabel *label_19;
    QLabel *labelverfA;
    QLabel *label_32;
    QPushButton *ColaFC;
    QPushButton *pushButton_13;
    QLabel *label_pedidos;
    QLabel *label_20;
    QLabel *label_3;
    QPushButton *pushButton_10;
    QLabel *labelColaC;
    QLabel *label_39;
    QLabel *balanceadorLabel;
    QLabel *label_26;
    QPushButton *pushButton_31;
    QPushButton *pushButton_28;
    QPushButton *BotonPedidos;
    QLabel *label_6;
    QPushButton *pushButton_17;
    QPushButton *pushButton_18;
    QPushButton *pushButton_19;
    QLabel *label_22;
    QLabel *label_5;
    QPushButton *pushButton_30;
    QPushButton *pushButton_16;
    QPushButton *pushButton_25;
    QPushButton *pushButton_27;
    QPushButton *pushButton_26;
    QLabel *label_35;
    QLabel *label_21;
    QLabel *label_24;
    QPushButton *pushButton_20;
    QLabel *label_23;
    QLabel *label_11;
    QLabel *label_8;
    QPushButton *pushButton_29;
    QLabel *label_13;
    QPushButton *BotonBalanceador;
    QLabel *label_7;
    QLabel *label_25;
    QLabel *label_12;
    QLabel *label_27;
    QPushButton *pushButton_15;
    QLabel *label_16;
    QPushButton *pushButton_38;
    QPushButton *pushButton_34;
    QPushButton *pushButton_37;
    QLabel *label_33;
    QLabel *label_34;
    QPushButton *pushButton_24;
    QLabel *label_9;
    QLabel *label_14;
    QPushButton *pushButton_21;
    QPushButton *pushButton_22;
    QLabel *label_10;
    QPushButton *pushButton_32;
    QPushButton *pushButton_33;
    QPushButton *pushButton_23;
    QLabel *label_38;
    QLabel *label_37;
    QLabel *label_42;
    QMenuBar *menubar;
    QStatusBar *statusbar;

    void setupUi(QMainWindow *MainWindow)
    {
        if (MainWindow->objectName().isEmpty())
            MainWindow->setObjectName("MainWindow");
        MainWindow->resize(800, 600);
        centralwidget = new QWidget(MainWindow);
        centralwidget->setObjectName("centralwidget");
        label = new QLabel(centralwidget);
        label->setObjectName("label");
        label->setGeometry(QRect(70, 0, 51, 41));
        label->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/estructuras/TP1 ED/imagenes/fabricas.png")));
        label->setScaledContents(true);
        ver_f4 = new QPushButton(centralwidget);
        ver_f4->setObjectName("ver_f4");
        ver_f4->setGeometry(QRect(120, 0, 41, 21));
        pushButton_FabricaMixta = new QPushButton(centralwidget);
        pushButton_FabricaMixta->setObjectName("pushButton_FabricaMixta");
        pushButton_FabricaMixta->setGeometry(QRect(0, 0, 71, 31));
        QIcon icon;
        icon.addFile(QString::fromUtf8("../../Desktop/estructuras/TP1 ED/imagenes/fabricas.png"), QSize(), QIcon::Normal, QIcon::Off);
        pushButton_FabricaMixta->setIcon(icon);
        pOsf4 = new QPushButton(centralwidget);
        pOsf4->setObjectName("pOsf4");
        pOsf4->setGeometry(QRect(120, 30, 71, 31));
        vercolaf4 = new QLabel(centralwidget);
        vercolaf4->setObjectName("vercolaf4");
        vercolaf4->setGeometry(QRect(0, 60, 51, 51));
        pOsfA = new QPushButton(centralwidget);
        pOsfA->setObjectName("pOsfA");
        pOsfA->setGeometry(QRect(340, 30, 71, 31));
        pushButton_12 = new QPushButton(centralwidget);
        pushButton_12->setObjectName("pushButton_12");
        pushButton_12->setGeometry(QRect(340, 100, 71, 31));
        colaFA = new QPushButton(centralwidget);
        colaFA->setObjectName("colaFA");
        colaFA->setGeometry(QRect(230, 0, 51, 20));
        label_2 = new QLabel(centralwidget);
        label_2->setObjectName("label_2");
        label_2->setGeometry(QRect(286, 70, 51, 41));
        label_2->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/estructuras/TP1 ED/imagenes/fabricas.png")));
        label_2->setScaledContents(true);
        labelCA = new QLabel(centralwidget);
        labelCA->setObjectName("labelCA");
        labelCA->setGeometry(QRect(230, 30, 51, 31));
        vercompfA = new QPushButton(centralwidget);
        vercompfA->setObjectName("vercompfA");
        vercompfA->setGeometry(QRect(340, 0, 31, 21));
        ColaFB = new QPushButton(centralwidget);
        ColaFB->setObjectName("ColaFB");
        ColaFB->setGeometry(QRect(230, 70, 51, 20));
        labelColaB = new QLabel(centralwidget);
        labelColaB->setObjectName("labelColaB");
        labelColaB->setGeometry(QRect(230, 100, 51, 31));
        label_4 = new QLabel(centralwidget);
        label_4->setObjectName("label_4");
        label_4->setGeometry(QRect(286, 0, 51, 41));
        label_4->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/estructuras/TP1 ED/imagenes/fabricas.png")));
        label_4->setScaledContents(true);
        pushButton_9 = new QPushButton(centralwidget);
        pushButton_9->setObjectName("pushButton_9");
        pushButton_9->setGeometry(QRect(340, 70, 31, 21));
        vercompf4 = new QLabel(centralwidget);
        vercompf4->setObjectName("vercompf4");
        vercompf4->setGeometry(QRect(110, 70, 61, 51));
        pushButton_2 = new QPushButton(centralwidget);
        pushButton_2->setObjectName("pushButton_2");
        pushButton_2->setGeometry(QRect(610, 100, 61, 21));
        pushButton_35 = new QPushButton(centralwidget);
        pushButton_35->setObjectName("pushButton_35");
        pushButton_35->setGeometry(QRect(610, 60, 31, 21));
        label_15 = new QLabel(centralwidget);
        label_15->setObjectName("label_15");
        label_15->setGeometry(QRect(570, 70, 37, 41));
        label_15->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/estructuras/TP1 ED/imagenes/facturar.png")));
        label_15->setScaledContents(true);
        label_19 = new QLabel(centralwidget);
        label_19->setObjectName("label_19");
        label_19->setGeometry(QRect(450, 80, 41, 41));
        labelverfA = new QLabel(centralwidget);
        labelverfA->setObjectName("labelverfA");
        labelverfA->setGeometry(QRect(430, 10, 51, 41));
        label_32 = new QLabel(centralwidget);
        label_32->setObjectName("label_32");
        label_32->setGeometry(QRect(710, 60, 51, 61));
        ColaFC = new QPushButton(centralwidget);
        ColaFC->setObjectName("ColaFC");
        ColaFC->setGeometry(QRect(270, 150, 51, 20));
        pushButton_13 = new QPushButton(centralwidget);
        pushButton_13->setObjectName("pushButton_13");
        pushButton_13->setGeometry(QRect(380, 180, 71, 31));
        label_pedidos = new QLabel(centralwidget);
        label_pedidos->setObjectName("label_pedidos");
        label_pedidos->setGeometry(QRect(50, 240, 71, 41));
        label_20 = new QLabel(centralwidget);
        label_20->setObjectName("label_20");
        label_20->setGeometry(QRect(460, 160, 61, 41));
        label_3 = new QLabel(centralwidget);
        label_3->setObjectName("label_3");
        label_3->setGeometry(QRect(326, 150, 51, 41));
        label_3->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/estructuras/TP1 ED/imagenes/fabricas.png")));
        label_3->setScaledContents(true);
        pushButton_10 = new QPushButton(centralwidget);
        pushButton_10->setObjectName("pushButton_10");
        pushButton_10->setGeometry(QRect(380, 150, 31, 21));
        labelColaC = new QLabel(centralwidget);
        labelColaC->setObjectName("labelColaC");
        labelColaC->setGeometry(QRect(260, 180, 51, 31));
        label_39 = new QLabel(centralwidget);
        label_39->setObjectName("label_39");
        label_39->setGeometry(QRect(470, 260, 61, 41));
        balanceadorLabel = new QLabel(centralwidget);
        balanceadorLabel->setObjectName("balanceadorLabel");
        balanceadorLabel->setGeometry(QRect(270, 230, 71, 41));
        label_26 = new QLabel(centralwidget);
        label_26->setObjectName("label_26");
        label_26->setGeometry(QRect(390, 370, 41, 61));
        pushButton_31 = new QPushButton(centralwidget);
        pushButton_31->setObjectName("pushButton_31");
        pushButton_31->setGeometry(QRect(460, 320, 61, 31));
        pushButton_28 = new QPushButton(centralwidget);
        pushButton_28->setObjectName("pushButton_28");
        pushButton_28->setGeometry(QRect(90, 490, 41, 21));
        BotonPedidos = new QPushButton(centralwidget);
        BotonPedidos->setObjectName("BotonPedidos");
        BotonPedidos->setGeometry(QRect(50, 290, 61, 31));
        QIcon icon1;
        icon1.addFile(QString::fromUtf8("../../Desktop/estructuras/TP1 ED/imagenes/pedidos.png"), QSize(), QIcon::Normal, QIcon::Off);
        BotonPedidos->setIcon(icon1);
        label_6 = new QLabel(centralwidget);
        label_6->setObjectName("label_6");
        label_6->setGeometry(QRect(220, 290, 41, 41));
        label_6->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/estructuras/TP1 ED/imagenes/balanceador.png")));
        label_6->setScaledContents(true);
        pushButton_17 = new QPushButton(centralwidget);
        pushButton_17->setObjectName("pushButton_17");
        pushButton_17->setGeometry(QRect(310, 460, 71, 31));
        pushButton_18 = new QPushButton(centralwidget);
        pushButton_18->setObjectName("pushButton_18");
        pushButton_18->setGeometry(QRect(310, 440, 41, 21));
        pushButton_19 = new QPushButton(centralwidget);
        pushButton_19->setObjectName("pushButton_19");
        pushButton_19->setGeometry(QRect(310, 520, 71, 31));
        label_22 = new QLabel(centralwidget);
        label_22->setObjectName("label_22");
        label_22->setGeometry(QRect(330, 340, 61, 31));
        label_5 = new QLabel(centralwidget);
        label_5->setObjectName("label_5");
        label_5->setGeometry(QRect(210, 300, 37, 12));
        pushButton_30 = new QPushButton(centralwidget);
        pushButton_30->setObjectName("pushButton_30");
        pushButton_30->setGeometry(QRect(90, 420, 41, 21));
        pushButton_16 = new QPushButton(centralwidget);
        pushButton_16->setObjectName("pushButton_16");
        pushButton_16->setGeometry(QRect(60, 370, 41, 31));
        pushButton_25 = new QPushButton(centralwidget);
        pushButton_25->setObjectName("pushButton_25");
        pushButton_25->setGeometry(QRect(310, 400, 71, 31));
        pushButton_27 = new QPushButton(centralwidget);
        pushButton_27->setObjectName("pushButton_27");
        pushButton_27->setGeometry(QRect(-20, 430, 71, 31));
        pushButton_26 = new QPushButton(centralwidget);
        pushButton_26->setObjectName("pushButton_26");
        pushButton_26->setGeometry(QRect(310, 380, 41, 21));
        label_35 = new QLabel(centralwidget);
        label_35->setObjectName("label_35");
        label_35->setGeometry(QRect(400, 510, 51, 31));
        label_21 = new QLabel(centralwidget);
        label_21->setObjectName("label_21");
        label_21->setGeometry(QRect(80, 390, 61, 31));
        label_24 = new QLabel(centralwidget);
        label_24->setObjectName("label_24");
        label_24->setGeometry(QRect(180, 420, 41, 51));
        pushButton_20 = new QPushButton(centralwidget);
        pushButton_20->setObjectName("pushButton_20");
        pushButton_20->setGeometry(QRect(310, 500, 41, 21));
        label_23 = new QLabel(centralwidget);
        label_23->setObjectName("label_23");
        label_23->setGeometry(QRect(130, 370, 51, 31));
        label_11 = new QLabel(centralwidget);
        label_11->setObjectName("label_11");
        label_11->setGeometry(QRect(270, 390, 41, 31));
        label_11->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/estructuras/TP1 ED/imagenes/alistadores.png")));
        label_11->setScaledContents(true);
        label_8 = new QLabel(centralwidget);
        label_8->setObjectName("label_8");
        label_8->setGeometry(QRect(270, 510, 41, 31));
        label_8->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/estructuras/TP1 ED/imagenes/alistadores.png")));
        label_8->setScaledContents(true);
        pushButton_29 = new QPushButton(centralwidget);
        pushButton_29->setObjectName("pushButton_29");
        pushButton_29->setGeometry(QRect(90, 440, 71, 31));
        label_13 = new QLabel(centralwidget);
        label_13->setObjectName("label_13");
        label_13->setGeometry(QRect(50, 430, 41, 31));
        label_13->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/estructuras/TP1 ED/imagenes/alistadores.png")));
        label_13->setScaledContents(true);
        BotonBalanceador = new QPushButton(centralwidget);
        BotonBalanceador->setObjectName("BotonBalanceador");
        BotonBalanceador->setGeometry(QRect(260, 290, 41, 21));
        label_7 = new QLabel(centralwidget);
        label_7->setObjectName("label_7");
        label_7->setGeometry(QRect(270, 450, 41, 31));
        label_7->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/estructuras/TP1 ED/imagenes/alistadores.png")));
        label_7->setScaledContents(true);
        label_25 = new QLabel(centralwidget);
        label_25->setObjectName("label_25");
        label_25->setGeometry(QRect(170, 490, 61, 51));
        label_12 = new QLabel(centralwidget);
        label_12->setObjectName("label_12");
        label_12->setGeometry(QRect(50, 500, 41, 31));
        label_12->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/estructuras/TP1 ED/imagenes/alistadores.png")));
        label_12->setScaledContents(true);
        label_27 = new QLabel(centralwidget);
        label_27->setObjectName("label_27");
        label_27->setGeometry(QRect(390, 440, 41, 51));
        pushButton_15 = new QPushButton(centralwidget);
        pushButton_15->setObjectName("pushButton_15");
        pushButton_15->setGeometry(QRect(260, 310, 71, 31));
        label_16 = new QLabel(centralwidget);
        label_16->setObjectName("label_16");
        label_16->setGeometry(QRect(570, 280, 37, 31));
        label_16->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/estructuras/TP1 ED/imagenes/empaque.png")));
        label_16->setScaledContents(true);
        pushButton_38 = new QPushButton(centralwidget);
        pushButton_38->setObjectName("pushButton_38");
        pushButton_38->setGeometry(QRect(610, 300, 71, 31));
        pushButton_34 = new QPushButton(centralwidget);
        pushButton_34->setObjectName("pushButton_34");
        pushButton_34->setGeometry(QRect(600, 200, 61, 31));
        pushButton_37 = new QPushButton(centralwidget);
        pushButton_37->setObjectName("pushButton_37");
        pushButton_37->setGeometry(QRect(610, 270, 31, 21));
        label_33 = new QLabel(centralwidget);
        label_33->setObjectName("label_33");
        label_33->setGeometry(QRect(700, 190, 61, 41));
        label_34 = new QLabel(centralwidget);
        label_34->setObjectName("label_34");
        label_34->setGeometry(QRect(710, 270, 61, 41));
        pushButton_24 = new QPushButton(centralwidget);
        pushButton_24->setObjectName("pushButton_24");
        pushButton_24->setGeometry(QRect(500, 440, 41, 21));
        label_9 = new QLabel(centralwidget);
        label_9->setObjectName("label_9");
        label_9->setGeometry(QRect(460, 510, 41, 31));
        label_9->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/estructuras/TP1 ED/imagenes/alistadores.png")));
        label_9->setScaledContents(true);
        label_14 = new QLabel(centralwidget);
        label_14->setObjectName("label_14");
        label_14->setGeometry(QRect(450, 390, 41, 31));
        label_14->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/estructuras/TP1 ED/imagenes/alistadores.png")));
        label_14->setScaledContents(true);
        pushButton_21 = new QPushButton(centralwidget);
        pushButton_21->setObjectName("pushButton_21");
        pushButton_21->setGeometry(QRect(500, 520, 71, 31));
        pushButton_22 = new QPushButton(centralwidget);
        pushButton_22->setObjectName("pushButton_22");
        pushButton_22->setGeometry(QRect(500, 500, 41, 21));
        label_10 = new QLabel(centralwidget);
        label_10->setObjectName("label_10");
        label_10->setGeometry(QRect(460, 450, 41, 31));
        label_10->setPixmap(QPixmap(QString::fromUtf8("../../Desktop/estructuras/TP1 ED/imagenes/alistadores.png")));
        label_10->setScaledContents(true);
        pushButton_32 = new QPushButton(centralwidget);
        pushButton_32->setObjectName("pushButton_32");
        pushButton_32->setGeometry(QRect(490, 400, 71, 31));
        pushButton_33 = new QPushButton(centralwidget);
        pushButton_33->setObjectName("pushButton_33");
        pushButton_33->setGeometry(QRect(490, 380, 41, 21));
        pushButton_23 = new QPushButton(centralwidget);
        pushButton_23->setObjectName("pushButton_23");
        pushButton_23->setGeometry(QRect(500, 460, 71, 31));
        label_38 = new QLabel(centralwidget);
        label_38->setObjectName("label_38");
        label_38->setGeometry(QRect(580, 500, 71, 51));
        label_37 = new QLabel(centralwidget);
        label_37->setObjectName("label_37");
        label_37->setGeometry(QRect(600, 450, 61, 41));
        label_42 = new QLabel(centralwidget);
        label_42->setObjectName("label_42");
        label_42->setGeometry(QRect(610, 380, 61, 41));
        MainWindow->setCentralWidget(centralwidget);
        menubar = new QMenuBar(MainWindow);
        menubar->setObjectName("menubar");
        menubar->setGeometry(QRect(0, 0, 800, 17));
        MainWindow->setMenuBar(menubar);
        statusbar = new QStatusBar(MainWindow);
        statusbar->setObjectName("statusbar");
        MainWindow->setStatusBar(statusbar);

        retranslateUi(MainWindow);

        QMetaObject::connectSlotsByName(MainWindow);
    } // setupUi

    void retranslateUi(QMainWindow *MainWindow)
    {
        MainWindow->setWindowTitle(QCoreApplication::translate("MainWindow", "MainWindow", nullptr));
        label->setText(QString());
        ver_f4->setText(QCoreApplication::translate("MainWindow", "Ver", nullptr));
        pushButton_FabricaMixta->setText(QCoreApplication::translate("MainWindow", "FabricaM", nullptr));
        pOsf4->setText(QCoreApplication::translate("MainWindow", "seguir/Parar", nullptr));
        vercolaf4->setText(QString());
        pOsfA->setText(QCoreApplication::translate("MainWindow", "seguir/Parar", nullptr));
        pushButton_12->setText(QCoreApplication::translate("MainWindow", "seguir/Parar", nullptr));
        colaFA->setText(QCoreApplication::translate("MainWindow", "FabricaA", nullptr));
        label_2->setText(QString());
        labelCA->setText(QString());
        vercompfA->setText(QCoreApplication::translate("MainWindow", "Ver", nullptr));
        ColaFB->setText(QCoreApplication::translate("MainWindow", "FabricaB", nullptr));
        labelColaB->setText(QString());
        label_4->setText(QString());
        pushButton_9->setText(QCoreApplication::translate("MainWindow", "Ver", nullptr));
        vercompf4->setText(QString());
        pushButton_2->setText(QCoreApplication::translate("MainWindow", "Parar/seguir", nullptr));
        pushButton_35->setText(QCoreApplication::translate("MainWindow", "Ver", nullptr));
        label_15->setText(QString());
        label_19->setText(QString());
        labelverfA->setText(QString());
        label_32->setText(QCoreApplication::translate("MainWindow", "TextLabel", nullptr));
        ColaFC->setText(QCoreApplication::translate("MainWindow", "FabricaC", nullptr));
        pushButton_13->setText(QCoreApplication::translate("MainWindow", "seguir/Parar", nullptr));
        label_pedidos->setText(QString());
        label_20->setText(QString());
        label_3->setText(QString());
        pushButton_10->setText(QCoreApplication::translate("MainWindow", "Ver", nullptr));
        labelColaC->setText(QString());
        label_39->setText(QCoreApplication::translate("MainWindow", "TextLabel", nullptr));
        balanceadorLabel->setText(QString());
        label_26->setText(QCoreApplication::translate("MainWindow", "TextLabel", nullptr));
        pushButton_31->setText(QCoreApplication::translate("MainWindow", "Alistados", nullptr));
        pushButton_28->setText(QCoreApplication::translate("MainWindow", "Ver", nullptr));
        BotonPedidos->setText(QCoreApplication::translate("MainWindow", "Pedidos", nullptr));
        label_6->setText(QString());
        pushButton_17->setText(QCoreApplication::translate("MainWindow", "seguir/Parar", nullptr));
        pushButton_18->setText(QCoreApplication::translate("MainWindow", "Ver", nullptr));
        pushButton_19->setText(QCoreApplication::translate("MainWindow", "seguir/Parar", nullptr));
        label_22->setText(QString());
        label_5->setText(QString());
        pushButton_30->setText(QCoreApplication::translate("MainWindow", "Ver", nullptr));
        pushButton_16->setText(QCoreApplication::translate("MainWindow", "Alisto", nullptr));
        pushButton_25->setText(QCoreApplication::translate("MainWindow", "seguir/Parar", nullptr));
        pushButton_27->setText(QCoreApplication::translate("MainWindow", "seguir/Parar", nullptr));
        pushButton_26->setText(QCoreApplication::translate("MainWindow", "Ver", nullptr));
        label_35->setText(QCoreApplication::translate("MainWindow", "TextLabel", nullptr));
        label_21->setText(QString());
        label_24->setText(QCoreApplication::translate("MainWindow", "TextLabel", nullptr));
        pushButton_20->setText(QCoreApplication::translate("MainWindow", "Ver", nullptr));
        label_23->setText(QString());
        label_11->setText(QString());
        label_8->setText(QString());
        pushButton_29->setText(QCoreApplication::translate("MainWindow", "seguir/Parar", nullptr));
        label_13->setText(QString());
        BotonBalanceador->setText(QCoreApplication::translate("MainWindow", "Ver", nullptr));
        label_7->setText(QString());
        label_25->setText(QCoreApplication::translate("MainWindow", "TextLabel", nullptr));
        label_12->setText(QString());
        label_27->setText(QCoreApplication::translate("MainWindow", "TextLabel", nullptr));
        pushButton_15->setText(QCoreApplication::translate("MainWindow", "seguir/Parar", nullptr));
        label_16->setText(QString());
        pushButton_38->setText(QCoreApplication::translate("MainWindow", "seguir/Parar", nullptr));
        pushButton_34->setText(QCoreApplication::translate("MainWindow", "Facturar", nullptr));
        pushButton_37->setText(QCoreApplication::translate("MainWindow", "Ver", nullptr));
        label_33->setText(QCoreApplication::translate("MainWindow", "TextLabel", nullptr));
        label_34->setText(QCoreApplication::translate("MainWindow", "TextLabel", nullptr));
        pushButton_24->setText(QCoreApplication::translate("MainWindow", "Ver", nullptr));
        label_9->setText(QString());
        label_14->setText(QString());
        pushButton_21->setText(QCoreApplication::translate("MainWindow", "seguir/Parar", nullptr));
        pushButton_22->setText(QCoreApplication::translate("MainWindow", "Ver", nullptr));
        label_10->setText(QString());
        pushButton_32->setText(QCoreApplication::translate("MainWindow", "seguir/Parar", nullptr));
        pushButton_33->setText(QCoreApplication::translate("MainWindow", "Ver", nullptr));
        pushButton_23->setText(QCoreApplication::translate("MainWindow", "seguir/Parar", nullptr));
        label_38->setText(QCoreApplication::translate("MainWindow", "TextLabel", nullptr));
        label_37->setText(QCoreApplication::translate("MainWindow", "TextLabel", nullptr));
        label_42->setText(QCoreApplication::translate("MainWindow", "TextLabel", nullptr));
    } // retranslateUi

};

namespace Ui {
    class MainWindow: public Ui_MainWindow {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_MAINWINDOW_H
